---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
df <- read.csv("activity.csv")
df_activity <- df[!is.na(df$steps), ]
```

## What is mean total number of steps taken per day?
```{r}
df_steps <- aggregate(steps ~ date, df_activity, sum)
hist(df_steps$steps, main = "Total number of steps taken each day",  xlab = "Steps")
mean(df_steps$steps)
median(df_steps$steps)
```

## What is the average daily activity pattern?
```{r}

step_averages <- aggregate(steps ~ interval, data = df_activity, FUN = mean)
plot(step_averages, type = "l", xlab = "5-minute interval", ylab = "Average number of steps taken")
step_averages[which.max(step_averages$steps), ]
```

## Imputing missing values
```{r}
sum(is.na(df$steps))


## Strategy is to replace NA by mean in 5 min interval
temp <- merge(df, step_averages, by = "interval", suffixes = c("", ".imputted"))
nas <- is.na(temp$steps)
temp$steps[nas] <- temp$steps.imputted[nas]
temp <- temp[, c(1:3)]

df_steps_imputted <- aggregate(steps ~ date, temp, sum)
hist(df_steps_imputted$steps, main ="Total number of steps taken each day (Imputted)",  xlab = "Steps")
mean(df_steps_imputted$steps)
median(df_steps_imputted$steps)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
day <- function(date) {
    if (weekdays(as.Date(date)) %in% c("Saturday", "Sunday"))
        "weekend"
    else "weekday"
}

df_activity$day_label <- as.factor(sapply(df_activity$date, day))
avg_steps <- aggregate(steps ~ interval + day_label, data = df_activity, mean)
library(lattice)
xyplot(steps ~ interval | day_label, avg_steps, type = "l", layout = c(1, 2), xlab = "5-minute interval", ylab = "Average number of steps")
```